// console.log(`Hello World`);
// window.alert(`This is alert`);
// let num=23;
// let name="Suyog Rai";
// let bool=true;
// console.log(`My name is $(firstName)`);
// document.getElementById("p1").textContent=`Your fullName is$ (name)`;
// let hi;
// hi=window.prompt("HI");                                     
let x="123";
let y="pizza";
let z="pizza";
x=Number(x);
y=String(y);
z=Boolean(z);
console.log(x);